apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountservice
  labels:
    app: accountservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accountservice
  template:
    metadata:
      labels:
        app: accountservice
    spec:
      containers:
      - name: accountservice
        image: accountservice:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3