apiVersion: apps/v1
kind: Deployment
metadata:
  name: quoteservice
  labels:
    app: quoteservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quoteservice
  template:
    metadata:
      labels:
        app: quoteservice
    spec:
      containers:
      - name: quoteservice
        image: quoteservice:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3